# -*- coding: utf-8 -*-
"""Diffusion_Check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jPI0cPBmBfDh3OLRUtYejA5F4uNRUhJ
"""

# ============ CELL 1: Install deps ============
!pip install pytorch-lightning==2.3.0 omegaconf einops
!pip install wandb natsort dctorch rasterio tifffile scipy opencv-python lpips s2cloudless
# !pip install natten==0.21.6 --no-build-isolation ==> this line is for colab
pip install natten==0.17.1+torch220cu121 -f https://shi-labs.com/natten/wheels

# Commented out IPython magic to ensure Python compatibility.
# ============ CELL 2: Clone repo ============
# %cd /content
!git clone https://github.com/weikaylee/cs159.git

# Commented out IPython magic to ensure Python compatibility.
# ============ CELL 3: Download data ============
# %cd /content/cs159
!python download_local_data.py

# ============ CELL 4: Download weights ============
!pip install gdown
!gdown --folder "https://drive.google.com/drive/folders/1T3OwRNP5r5qVLQZujnl2WDBVXHC1Am65" -O /content/emrdm_weights

# ============ CELL 5: Fix pkl files ============
import pickle, glob, os

data_root = "/content/cs159/data"
s2_files = glob.glob(f"{data_root}/ROIs1158_spring_s2/**/*.tif", recursive=True)

triplets = []
for s2_path in s2_files:
    basename = os.path.basename(s2_path)
    suffix = basename.replace("ROIs1158_spring_s2_", "").replace(".tif", "")
    scene = suffix.split("_p")[0]
    s1_rel  = f"ROIs1158_spring_s1/s1_{scene}/ROIs1158_spring_s1_{suffix}.tif"
    s2_rel  = f"ROIs1158_spring_s2/s2_{scene}/ROIs1158_spring_s2_{suffix}.tif"
    s2c_rel = f"ROIs1158_spring_s2_cloudy/s2_cloudy_{scene}/ROIs1158_spring_s2_cloudy_{suffix}.tif"
    if os.path.exists(os.path.join(data_root, s1_rel)) and os.path.exists(os.path.join(data_root, s2c_rel)):
        triplets.append({"S1": s1_rel, "S2": s2_rel, "S2_cloudy": s2c_rel})

n = len(triplets)
train = triplets[:int(0.7*n)]
val   = triplets[int(0.7*n):int(0.85*n)]
test  = triplets[int(0.85*n):]

for split, data in [("train", train), ("val", val), ("test", test)]:
    with open(f"{data_root}/all_{split}_paths.pkl", "wb") as f:
        pickle.dump(data, f)
    print(f"{split}: {len(data)} samples")

# ============ CELL 6: Edit yaml ============
EMRDM = "/content/EMRDM"
with open(f"{EMRDM}/configs/example_training/sentinel.yaml") as f:
    content = f.read()

content = content.replace(
    '# ckpt_path: "" # your checkpoint path',
    'ckpt_path: "/content/emrdm_weights/train/sentinel/checkpoints/last.ckpt"'
)
content = content.replace(
    'root: "/remote-home/share/dmb_nas2/liuyi/SEN12MSCR"',
    'root: "/content/cs159/data"'
)
content = content.replace(
    'devices: 2,4',
    'devices: "1"'
)

with open(f"{EMRDM}/configs/example_training/sentinel_colab.yaml", "w") as f:
    f.write(content)

print("yaml written")

transformer_path = "/content/EMRDM/sgm/modules/diffusionmodules/k_diffusion/image_transformer.py"

with open(transformer_path) as f:
    code = f.read()

# Fix the separate qk+av path
old = """B,H,X,Y,D = q.shape; _qk = torch.matmul(q.reshape(B,H,X*Y,D), k.reshape(B,H,X*Y,D).transpose(-2,-1)); _a = torch.softmax(_qk, dim=-1).to(v.dtype); x = torch.matmul(_a, v.reshape(B,H,X*Y,D)).reshape(B,H,X,Y,D)"""
new = """B,H,X,Y,D = q.shape; _qk = torch.matmul(q.reshape(B*H,X*Y,D), k.reshape(B*H,X*Y,D).transpose(-2,-1)); _a = torch.softmax(_qk, dim=-1).to(v.dtype); x = torch.matmul(_a, v.reshape(B*H,X*Y,D)).reshape(B,H,X,Y,D)"""

# Fix the av path
old2 = """B,H,X,Y,_ = qk.shape; x = torch.matmul(a, v.reshape(B,H,X*Y,v.shape[-1])).reshape(B,H,X,Y,v.shape[-1])"""
new2 = """B,H,X,Y,D = q.shape; x = torch.matmul(a.reshape(B*H,X*Y,X*Y), v.reshape(B*H,X*Y,D)).reshape(B,H,X,Y,D)"""

code = code.replace(old, new)
code = code.replace(old2, new2)

with open(transformer_path, "w") as f:
    f.write(code)

print("patched")

import pickle, os

# Check data
with open("/content/cs159/data/all_test_paths.pkl", "rb") as f:
    test = pickle.load(f)
print(f"Test samples: {len(test)}")
print(f"Sample entry: {test[0]}")

# Check first tif exists
s2_path = os.path.join("/content/cs159/data", test[0]["S2"])
print(f"S2 exists: {os.path.exists(s2_path)}")

# Check checkpoint
print(f"Checkpoint exists: {os.path.exists('/content/emrdm_weights/train/sentinel/checkpoints/last.ckpt')}")

# Check patch
!grep -n "natten.functional\|na2d" /content/EMRDM/sgm/modules/diffusionmodules/k_diffusion/image_transformer.py

# ============ CELL 7: Run inference ============
import os
os.chdir(EMRDM)

!python main.py \
    --base configs/example_training/sentinel_colab.yaml \
    --enable_tf32 \
    -t false \
    --no-test true \
    --predict true

!find /content/EMRDM/logs -name "*.tif" -o -name "*.png" | head -20

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import glob

sample_dir = "/content/EMRDM/logs/2026-05-22T04-51-27_example_training-sentinel_colab/sample"

# Show one patch: cloudy input (mu), prediction, and ground truth
patches = ["p100", "p101", "p103", "p104", "p504"]

fig, axes = plt.subplots(len(patches), 3, figsize=(12, 4*len(patches)))
for i, p in enumerate(patches):
    for j, (suffix, title) in enumerate([("_mu.png", "Input (mu)"), (".png", "Prediction"), ("_target.png", "Ground Truth")]):
        path = glob.glob(f"{sample_dir}/*{p}{suffix}")
        if path:
            img = mpimg.imread(path[0])
            axes[i,j].imshow(img)
            axes[i,j].set_title(f"{p} {title}")
            axes[i,j].axis("off")

plt.tight_layout()
plt.savefig("/content/results_comparison.png", dpi=150)
plt.show()
print("done")

