#!/usr/bin/env python3
"""Train EMRDM from scratch on mirror-space Sentinel-2 data.

Prerequisites
-------------
1. Mirror pkl files must exist under data_root (generated by prepare_mirror_dataset.py):
       all_train_paths_mirror.pkl
       all_val_paths_mirror.pkl
       all_test_paths_mirror.pkl
2. natten must be installed.
3. Run from phase2_emrdm/ (or let train_emrdm.sh handle the cd).

Usage
-----
    cd phase2_emrdm
    python train_emrdm.py \\
        --data_root ../data \\
        --devices 2 \\
        --wandb
"""

import argparse
import os
import pickle
import subprocess
import sys

CODE_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CONFIG = os.path.join(
    "configs", "example_training", "sentinel_mirror_train_scratch.yaml"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train EMRDM from scratch on mirror-space data."
    )
    parser.add_argument(
        "--data_root",
        default=os.path.join(CODE_DIR, "..", "data"),
        help="Root dir containing mirror pkl files and scene TIFs.",
    )
    parser.add_argument(
        "--config",
        default=DEFAULT_CONFIG,
        help="Base YAML config (relative to phase2_emrdm/).",
    )
    parser.add_argument(
        "--devices",
        type=int,
        default=2,
        help="Number of GPUs for Lightning trainer.",
    )
    parser.add_argument("--wandb", action="store_true", help="Enable W&B logging.")
    parser.add_argument("--wandb_project", default="cs159", help="W&B project name.")
    parser.add_argument(
        "--logdir", default="logs", help="Lightning log directory (-l flag)."
    )
    parser.add_argument(
        "--resume",
        default="",
        help="Resume interrupted training from this checkpoint (-r flag).",
    )
    return parser.parse_args()


def check_prerequisites(data_root: str) -> None:
    if not os.path.isdir(data_root):
        sys.exit(f"ERROR: data_root does not exist: {data_root}")

    required_pkls = [
        "all_train_paths_mirror.pkl",
        "all_val_paths_mirror.pkl",
        "all_test_paths_mirror.pkl",
    ]
    for fname in required_pkls:
        pkl_path = os.path.join(data_root, fname)
        if not os.path.isfile(pkl_path):
            sys.exit(
                f"ERROR: missing pkl file: {pkl_path}\n"
                "Run prepare_mirror_dataset.py first."
            )
        with open(pkl_path, "rb") as f:
            samples = pickle.load(f)
        split = fname.replace("all_", "").replace("_paths_mirror.pkl", "")
        print(f"  {split}: {len(samples)} mirror triplets")


def main() -> None:
    args = parse_args()
    data_root = os.path.abspath(args.data_root)

    print("=== Checking prerequisites ===")
    check_prerequisites(data_root)

    print("=== Applying natten patch ===")
    from run_emrdm_predict import patch_natten
    patch_natten()

    # OmegaConf dotlist overrides — consumed by main.py's unknown-args parser.
    overrides = [
        f"data.params.train.params.root={data_root}",
        f"data.params.validation.params.root={data_root}",
        f"data.params.test.params.root={data_root}",
        f"data.params.predict.params.root={data_root}",
        f"lightning.trainer.devices={args.devices}",
    ]

    cmd = [
        sys.executable, "main.py",
        "--base", args.config,
        "-l", args.logdir,
        *overrides,
    ]
    if args.wandb:
        cmd += ["--wandb", "--projectname", args.wandb_project]
    if args.resume:
        cmd += ["-r", args.resume]

    print("=== Launching training ===")
    print(" ".join(cmd))
    result = subprocess.run(cmd, cwd=CODE_DIR)
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
